server:
  port: 8085

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: xbrVmML8igOquiucHFwjfjN31PX2D8Dc
            scope: openid,profile,email
            redirect-uri: http://localhost:8085/login/oauth2/code/keycloak
#            client-name: oauth2-client-app
#            authorization-grant-type: authorization_code
#            client-authentication-meth                               od: client_secret_basic
        provider:
          keycloak:
            issuer-uri: http://localhost:8200/realms/oauth2
#            authorization-uri: http://localhost:8200/realms/oauth2/protocol/openid-connect/auth
#            token-uri: http://localhost:8200/realms/oauth2/protocol/openid-connect/token
#            user-info-uri: http://localhost:8200/realms/oauth2/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8200/realms/oauth2/protocol/openid-connect/certs
#            user-name-attribute: preferred_username


